services:
  api-gateway:
    build:
      context: .
    image: invenlore/invenlore-api-gateway
    container_name: invenlore-api-gateway
    hostname: invenlore-api-gateway
    networks:
      - invenlore-network
    ports:
      - 80:80
      - 8080:8080
    environment:
      - APP_ENV=dev
      - APP_LOG_LEVEL=DEBUG
      - HTTP_PORT=8080
      - HEALTH_PORT=80
      - SERVICE_HEALTH_TIMEOUT=30s
      - IDENTITY_SERVICE_ENDPOINT=invenlore-identity-service:8081
    deploy:
      restart_policy:
        condition: on-failure

networks:
  invenlore-network:
    external: true
